name: test
on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: npm run prettier
      - run: npm run cspell
      - run: npm run markdownlint
      - run: npm test
      - run: npm run build
      - run: npm run linkcheck

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: npm run build
      - run: npx playwright install --with-deps chromium
      - run: npm run test:e2e
